<script type="text/javascript">
	<mw:if test="!(Request.Path.toLower.endsWith('/preview') || Request.Path.toLower.endsWith('/preview/'))">
		var defaultMobile;
		var defaultDesktop;
		var mobileToDesktop = {
			'm.treinamento2.mundiware.com': defaultDesktop = 'treinamento2.mundiware.com',
            'm.dev.treinamento2.mundiware.com': 'dev.treinamento2.mundiware.com'
		};
		var desktopToMobile = {
			'treinamento2.mundiware.com': defaultMobile = 'm.treinamento2.mundiware.com',
            'dev.treinamento2.mundiware.com': 'm.dev.treinamento2.mundiware.com'
		};
		
		function checkWidth() {
			
			var newUrl = new URL(location);
			
			if(newUrl.searchParams.get('auto-redirect') == 'false' || newUrl.searchParams.get('auto-redirect') == '0') {
				return;
			}
			
			if (window.screen.width >= 1024 && desktopToMobile[newUrl.host] == null) {
				newUrl.host = mobileToDesktop[newUrl.host] || defaultDesktop;
			}
			else if (window.screen.width < 1024 && mobileToDesktop[newUrl.host] == null) {
				newUrl.host = desktopToMobile[newUrl.host] || defaultMobile;
			}
			
			if(newUrl.toString() != location.toString()) {
				location.href = newUrl.toString();
			}
		}
		
		if(window.addEventListener) {
			window.addEventListener('resize', checkWidth);
		} else if(window.attachEvent) {
			window.attachEvent('onresize', checkWidth);
		} else {
			window['onresize'] = checkWidth
		}
		
		checkWidth();
	</mw:if>
</script>